api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import CursViewSet, StudentViewSet

router = routers.DefaultRouter()
router.register('curs', CursViewSet) #/api/curs
router.register('student', StudentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace="rest_framework"))
]

curs/urls.py
from django.urls import path
from .views import hello, show_students, show_student, show_curs,\
     contact, add_student, edit_student, login_view, logout_view, api_student, xss_example 

urlpatterns = [
    path('', hello),
    path('students/', show_students, name="student_list"),
    path('student/<int:student_id>/', show_student, name="student_detail"),
    path('curs/<int:curs_id>/', show_curs, name="curs_detail"),
    path('contact', contact),
    path('add_student', add_student),
    path('edit_student/<int:student_id>/', edit_student),
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),

    path('api/student/<int:student_id>', api_student),
    path('xss/', xss_example),

] 

siit/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('curs/', include('curs.urls')),
    path('api/', include('api.urls')),
    path('__debug__/', include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

curs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Curs(models.Model):
    nume = models.CharField(max_length=20)

    def __str__(self):
        return self.nume


class StudentManager(models.Manager):

    def seniors(self):
        return self.filter(an=4)


class Student(models.Model):
    class Meta:
        ordering = ("nume", )
        unique_together = ("nume", "prenume")

    nume = models.CharField(max_length=20)
    prenume = models.CharField(max_length=20, db_index=True)
    cursuri = models.ManyToManyField(Curs)
    an = models.IntegerField(default=1)
    
    objects = StudentManager()

    def __str__(self):
        course_count = self.cursuri.count()
        if course_count:
            return f'{self.prenume} {self.nume} {course_count}'
        else:
            return f'{self.prenume} {self.nume}'
    
    def metoda_mea(self):
        pass

 

class Note(models.Model):
    nota = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.student} {self.nota}'

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cod_postal = models.CharField(max_length=20)

curs/forms.py
from django import forms

from .models import Student

class ContactForm(forms.Form):
    nume = forms.CharField(max_length=20)
    email = forms.EmailField()
    message = forms.CharField(max_length=100, widget=forms.Textarea)

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)

api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from .serializers import CursSerializer, StudentSerializer
from curs.models import Curs, Student


class CursViewSet(viewsets.ModelViewSet):
    queryset = Curs.objects.all()
    serializer_class = CursSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]


class StudentViewSet(viewsets.ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = super().get_queryset()
        search = self.request.query_params.get('search')
        if search:
            qs = qs.filter(nume__icontains=search)
        return qs

curs/views.py
import json
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from django.db.models import Q
from django.core.mail import send_mail
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import ContactForm, StudentForm, LoginForm
from .models import Student, Curs
from .decorators import view_counter, decorator1

from django.utils import timezone

def my_func():
    return 'func'

@view_counter
@decorator1
def hello(request):
    request.session['today'] = str(timezone.now())
    my_dict = {
        'unu': 1,
        'doi': 2
    }
    my_list = [1,2,3]
    ctx = { 
        'name': 'dorel',
        'my_dict': my_dict,
        'my_list': my_list,
        'my_func': my_func 
    }
    if True:
        del ctx['my_dict']
    return render(request, "index.html", ctx)

def show_students(request):
    if 'search' in request.GET:
        search = request.GET['search']
        lista_studenti = Student.objects.filter(Q(nume__iexact=search) | Q(prenume__iexact=search))
        print(str(lista_studenti.query))
    else:
        lista_studenti = Student.objects.prefetch_related('cursuri').all()
    return render(request, "show_students.html", {"students": lista_studenti})

def show_student(request, student_id):
    request.session['view_count'] = request.session.get('view_count', 0) + 1
    key = f'cache_{student_id}'
    student = cache.get(key, None)
    if student is None:
        print("miss", key)
        #student = get_object_or_404(Student, pk=student_id)
        student = Student.objects.prefetch_related('cursuri').get(pk=student_id)
        cache.set(key, student, 15)    
    # try:
    #     student = Student.objects.get(pk=student_id)
    #     render()
    # except Student.DoesNotExist:
    #     return 404
    return render(request, "show_student.html", {"student": student})

@cache_page(60)
def show_curs(request, curs_id):
    curs = get_object_or_404(Curs, id=curs_id)
    return render(request, "show_curs.html", {"curs": curs})

def add_student(request):
    if request.method == "POST":
        student_form = StudentForm(request.POST)
        if student_form.is_valid():
            student_form.save()
    else:
        student_form = StudentForm(initial = {"nume": "Dorel"})
    return render(request, "add_student.html", {"form": student_form})

def edit_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    saved = False
    if request.method == "POST":
        student_form = StudentForm(request.POST, instance=student)
        if student_form.is_valid():
            student_form.save()
            saved = True
        
    else:
        student_form = StudentForm(instance=student)
    return render(request, "add_student.html", {"form": student_form, "saved": saved})

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            send_mail('subject',
                form.cleaned_data['message'],
                [form.cleaned_data['email']],
                ['contact@domeniu.com'])
        else:
            form_data = {}
    else:
        form = ContactForm()
        form_data = {}
    return render(request, "contact.html", {'form': form, 'form_data': form_data})


def login_view(request):
    error_message = None
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.info(request, "User logat cu success")
                return redirect('/curs')
            else:
                messages.error(request, "Nu avem acest user")
    form = LoginForm()
    return render(request, "login.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect('/curs')


def api_student(request, student_id):
     student = get_object_or_404(Student, pk=student_id)

     context = {
        "nume": student.nume.upper(),
        "prenume": student.prenume.upper()
     }
     
     return HttpResponse(json.dumps(context), content_type="application/json")

def xss_example(request):
    context = {
        "user_input": request.GET.get("foo")
    }
    return render(request, "example.html", context)

curs/templates/add_student.html
{% extends "base.html" %}
{% block title %} Adaugare student {% endblock title %}
{% block body %} 
{% if saved %}
<div style="color:green"> Salvat cu success!</div>
{% endif %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salveaza!" />
</form>
{% endblock %}

curs/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Default title{% endblock %}</title>
        <style type="text/css">
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            }
        </style>
    </head>
    <body>
        {% block body %}
        Default body
        {% endblock %}
        <footer>
        Copyright 2021 - Current user : {{ request.user }}
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
            <div>
                <h6>Messages from Django</h6>
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div style="color:red">
                        {{ message }}
                    </div>
                    {% else %}
                        {{ message }}
                    {% endif %}
                {% endfor %}
            </div>
        </footer>
    </body>
</html>

curs/templates/contact.html
{% extends "base.html" %}
{% block title %} Contact {% endblock title %}
{% block body %}
Contact
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {% for field in form %}
            {{field.label }} - {{ field }} <br />
            {% if field.errors %} <div style="color:red">{{ field.errors }}</div> {% endif %}
        {% endfor %}
        <input type="submit" value="Send!" />
    </form>
</div>
<div>
    Form data
    {{ form_data }}
</div>
{% endblock %}

curs/templates/example.html
{% extends "base.html" %}

{% block body %}
  {{ user_input |safe }}
{% endblock %}

curs/templates/includes/sidebar.html
<ul>
    <li>Menu</li>
    {{ student }}
</ul>

curs/templates/index.html
{% extends "base.html" %}
{% block title %} {{ block.super }} test {% endblock %}
{% block body %}
        <h1>Hello 1</h1>
        {{ name | title }}
        <br />
        {{ my_dict.unu }}
        {{ my_dict.doi }}
        {{ my_dict.no_key }}
        <br /> Lista
        {{ my_list.0 }}
        {{ my.list.100 }}
        <br />
        {{ my_func }}
        {{ request.user }}
        {{ scoala }}
        <div>
        {{ request.GET }}
        {{ request.POST}}
        {{ request.session.hello }}
        request.custom = {{ request.custom}}
</div>
{% endblock %}

curs/templates/login.html
{% extends "base.html" %} 
{% block body %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login!" />
</form>
{% endblock body %}

curs/templates/show_curs.html
{% extends "base.html" %}
{% block body %}
<h1>{{ curs.nume }} </h1>
        <div>
            <h2> Students</h2>
            <ul>
            {% for student in curs.student_set.all %}
                <li> {{ student }} </li>
                {% empty %} <li> Nu sunt studenti</li>
            {% endfor %}
            </ul>
        </div>
{% endblock body %}

curs/templates/show_student.html
{% extends "base.html" %}
{% load filtre_curs %}

{% block title %} {{student}} {% endblock title %}
{% block body %}
        {{ student | my_title:"aaa" }} <br />
        {{ student.an}}
        {% my_tag %}
        <div>
            <h1>Cursuri</h1>
            <ul>
             {% for curs in student.cursuri.all %}
                <li> {{ curs }} </li>
                {% empty %} <li>Nu sunt cursuri asociate acestui student </li>
             {% endfor %}
             </ul>
        </div>
        <div>
            <a href="{% url 'student_list' %}">Inapoi la pagina principala</a>
        </div>
        <div>
            Vizualizari: {{ request.session.view_count }}
        </div>
        {% include 'includes/sidebar.html' %}
{% endblock %}

curs/templates/show_students.html
{% load static %}
<html>
    <head>
        <title>Student List</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    </head>
    <body>
        <h1>Student List</h1>
        <ul>
            {% for student in students %}
                <li> 
                    <a href="{% url 'student_detail' student.pk %}"> {{ student }} </a> 
                </li>
            {% empty %} Nu s-au gasit rezultate 
            {% endfor %}
        </ul>
    </body>
</html>

curs/templates/signup.html
{% extends "base.html" %}
{% block body %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}